apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boutique

resources:
  - https://github.com/GoogleCloudPlatform/microservices-demo//kustomize/base?ref=v0.10.6

patches:
  - path: patches/otel-tracing.yaml
  - path: patches/cartservice-resources.yaml
